POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json
 
{
 "username": "krishna",
 "name": "Adam Richard",
 "password": "l_567",
 "gender": "male",
 "location": "Detroit"
}
###

GET http://localhost:3000/ HTTP/1.1
###

POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json
 
{
  "username": "adam_richard",
  "password": "richard_567"
}
###

PUT http://localhost:3000/change-password HTTP/1.1
Content-Type: application/json
 
{
  "username": "adam_richard",
  "oldPassword": "richard@123",
  "newPassword": "richard_567"
}
###
